name: Deploy to King-sj.github.io

on:
  push:
    branches:
      - master
env:
  SSH_PORT: 22

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run docs:build
      - name: output result
        run: |
          ls -a blog/.vuepress/dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN}}
          publish_dir: blog/.vuepress/dist # 或者您项目构建输出的目录
          external_repository: King-sj/King-sj.github.io
          publish_branch: main
